on:
  push:
    branches:
      - main
      - master
jobs:
  verify:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URI }}
      - name: Collect coverage from client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client
      - name: Collect coverage from server
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URL }}
